version: "3"
services:

  wasm-add:
    build:
      dockerfile: wasm-add.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-sub:
    build:
      dockerfile: wasm-sub.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-min:
    build:
      dockerfile: wasm-min.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-mul:
    build:
      dockerfile: wasm-mul.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-div:
    build:
      dockerfile: wasm-div.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-max:
    build:
      dockerfile: wasm-max.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-power:
    build:
      dockerfile: wasm-power.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-modulus:
    build:
      dockerfile: wasm-modulus.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-concat:
    build:
      dockerfile: wasm-concat.Dockerfile
    volumes:
      - ./modules:/modules