version: "3"
services:

  wasm-add:
    build:
      dockerfile: wasm-add.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-sub:
    build:
      dockerfile: wasm-sub.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-min:
    build:
      dockerfile: wasm-min.Dockerfile
    volumes:
      - ./modules:/modules

  wasm-mul:
    build:
      dockerfile: wasm-mul.Dockerfile
    volumes:
      - ./modules:/modules